spring.application.name=spring-batch
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/spring_batch?allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${SPRING_BATCH_DBPASS}

spring.universitydatasource.jdbc-url=jdbc:mysql://localhost:3306/university?allowPublicKeyRetrieval=true
spring.universitydatasource.username=root
spring.universitydatasource.password=${SPRING_BATCH_DBPASS}

spring.postgresdatasource.jdbc-url=jdbc:postgresql://localhost:5432/university
spring.postgresdatasource.username=postgres
spring.postgresdatasource.password=${SPRING_BATCH_PGDBPASS}

#org.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.infybuzz=debug